# This file is generated by the scaffold script below.
# Replace or extend as you iterate—keep it simple and readable.

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

os.makedirs("reports/tables", exist_ok=True)
os.makedirs("reports/figures", exist_ok=True)

df = pd.read_csv("data/sample/mariners_kpi.csv")

singles = df["H"] - (df["2B"] + df["3B"] + df["HR"])
tb = singles + 2*df["2B"] + 3*df["3B"] + 4*df["HR"]

ab = df["AB"].replace(0, pd.NA)
obp_den = (df["AB"] + df["BB"] + df["HBP"] + df["SF"]).replace(0, pd.NA)

df["AVG"] = (df["H"] / ab).astype(float)
df["SLG"] = (tb / ab).astype(float)
df["OBP"] = ((df["H"] + df["BB"] + df["HBP"]) / obp_den).astype(float)
df["OPS"] = df["OBP"] + df["SLG"]

summary = df[["player","AVG","OBP","SLG","OPS"]].sort_values("OPS", ascending=False)
summary.to_csv("reports/tables/kpi_summary.csv", index=False)

plt.figure()
plt.bar(summary["player"], summary["OPS"])
plt.title("Top OPS — sample")
plt.xticks(rotation=20)
plt.tight_layout()
plt.savefig("reports/figures/ops_top.png", dpi=160)
print("Wrote reports/tables/kpi_summary.csv and reports/figures/ops_top.png")

